apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-cloud-gateway
  labels:
    app: hc-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hc-cloud-gateway
  template:
    metadata:
      labels:
        app: hc-cloud-gateway
    spec:
      containers:
        - name: hc-cloud-gateway
          image: valere1991/hc-cloud-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: hc-cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: hc-cloud-gateway
