apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-web
  labels:
    app: angular-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-web
  template:
    metadata:
      labels:
        app: angular-web
    spec:
      containers:
        - name: angular-web
          image: valere1991/web-angular:8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: angular-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular-web
