apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-notification-service
  labels:
    app:  hc-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hc-notification-service
  template:
    metadata:
      labels:
        app:  hc-notification-service
    spec:
      containers:
        - name:  hc-notification-service
          image: valere1991/hc-notification-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007

---
apiVersion: v1
kind: Service
metadata:
  name:  hc-notification-service-svc
spec:
  ports:
    - targetPort: 5007
      protocol: TCP
      port: 80
  selector:
    app: hc-notification-service
