apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-product-service
  labels:
    app:  hc-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hc-product-service
  template:
    metadata:
      labels:
        app:  hc-product-service
    spec:
      containers:
        - name:  hc-product-service
          image: valere1991/hc-product-service:7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name:  hc-product-service-svc
spec:
  ports:
    - targetPort: 5003
      protocol: TCP
      port: 80
  selector:
    app: hc-product-service
