apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hc-service-registry
spec:
  serviceName: "hc-service-registry"
  replicas: 1
  selector:
    matchLabels:
      app: hc-service-registry
  template:
    metadata:
      labels:
        app: hc-service-registry
    spec:
      containers:
        - name: hc-service-registry
          image: valere1991/hc-service-registry:8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: hc-service-registry
spec:
  selector:
    app: hc-service-registry
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8761
